# -*- coding: utf-8 -*-
"""time kovai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1equ9_lMd4ngdjmqQ_fKWArbctPftGPG4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/Daily_Public_Transport_Passenger_Boardings_By_Ticket_Type_20240513.csv")
data.head()

data=data.drop(['Paper Ticket'],axis=1)
data

data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')
df = data.loc[(data['Date'] <= '30-04-2024')]

df.dtypes

sns.set_style('whitegrid')
df.plot(figsize = (13,7), title ='MyWay', color = 'orangered')
plt.show()

df1=df['MyWay']

rolmean = df1.rolling(window=15).mean()
rolstd = df1.rolling(window=15).std()

plt.figure(figsize = (13,7))
orig = plt.plot(df, color = 'green', label = 'Original')
mean = plt.plot(rolmean, color = 'orange', label = 'Rolling Mean')
std = plt.plot(rolstd, color = 'black', label = 'Rolling Std')
plt.legend(loc='best')
plt.title('Rolling Mean & Standard Deviation')
plt.show(block=True)

from statsmodels.tsa.arima.model import ARIMA
model = ARIMA(df1, order=(5,1,0))
fit_model = model.fit()
forecast = fit_model.forecast(steps=7)
print("Forecast for the next 7 days is :")
print(forecast)

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

plt.figure(figsize = (12,7))
plt.subplot(211)
plot_acf(df1, ax=plt.gca(),lags=30)
plt.subplot(212)
plot_pacf(df1, ax=plt.gca(),lags=30)
plt.show()

